# Generated by Django 4.1.2 on 2022-12-21 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_remove_post_header_image_post_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='facebook_url',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='instagram_url',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='twitter_url',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='whatsapp_url',
        ),
    ]
