# Generated by Django 4.1.2 on 2022-12-21 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_remove_userprofile_facebook_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='status',
        ),
    ]
