# Generated by Django 4.1.2 on 2022-12-21 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_post_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='status',
        ),
    ]
