# Generated by Django 4.1.2 on 2023-01-29 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_featuredpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeaturedPost',
        ),
    ]
