# Generated by Django 4.1.2 on 2023-01-30 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_post_section_post_status_userprofile_birthday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredpost',
            name='section',
            field=models.CharField(choices=[('Popular', 'Popular'), ('Recent', 'Recent'), ('Trending', 'Trending'), ('Latest Posts', 'Latest Posts')], default='Recent', max_length=200),
        ),
        migrations.AddField(
            model_name='featuredpost',
            name='status',
            field=models.CharField(choices=[('0', 'Draft'), ('1', 'Publish')], default=0, max_length=100, null=True),
        ),
    ]
