# Generated by Django 4.1.2 on 2023-01-30 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_featuredpost_section_featuredpost_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='facebook_url',
            field=models.CharField(default='https://www.yourfacebooklink.com', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='instagram_url',
            field=models.CharField(default='https://www.yourinstagramlink.com', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='linkedin_url',
            field=models.CharField(default='https://www.yourlinkedinlink.com', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='twitter_url',
            field=models.CharField(default='https://www.yourtwitterlink.com', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='youtube_url',
            field=models.CharField(default='https://www.youryoutubelink.com', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='website_url',
            field=models.CharField(default='https://www.yourwebsitelink.com', max_length=300, null=True),
        ),
    ]
