# Generated by Django 4.1.2 on 2023-01-31 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_userprofile_facebook_url_userprofile_instagram_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='section1',
            field=models.CharField(choices=[('Popular', 'Popular'), ('Recent', 'Recent'), ('Trending', 'Trending'), ('Latest Posts', 'Latest Posts')], default='Recent', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='section2',
            field=models.CharField(choices=[('Popular', 'Popular'), ('Recent', 'Recent'), ('Trending', 'Trending'), ('Latest Posts', 'Latest Posts')], default='Recent', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='section3',
            field=models.CharField(choices=[('Popular', 'Popular'), ('Recent', 'Recent'), ('Trending', 'Trending'), ('Latest Posts', 'Latest Posts')], default='Recent', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='section',
            field=models.CharField(choices=[('Popular', 'Popular'), ('Recent', 'Recent'), ('Trending', 'Trending'), ('Latest Posts', 'Latest Posts')], default='Recent', max_length=200, null=True),
        ),
    ]
