# Generated by Django 4.1.2 on 2023-01-31 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_post_section1_post_section2_post_section3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredpost',
            name='section1',
            field=models.CharField(choices=[('Popular', 'Popular'), ('Recent', 'Recent'), ('Trending', 'Trending'), ('Latest Posts', 'Latest Posts')], default='Recent', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='featuredpost',
            name='section2',
            field=models.CharField(choices=[('Popular', 'Popular'), ('Recent', 'Recent'), ('Trending', 'Trending'), ('Latest Posts', 'Latest Posts')], default='Recent', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='featuredpost',
            name='section3',
            field=models.CharField(choices=[('Popular', 'Popular'), ('Recent', 'Recent'), ('Trending', 'Trending'), ('Latest Posts', 'Latest Posts')], default='Recent', max_length=200, null=True),
        ),
    ]
