# Generated by Django 4.1.2 on 2023-02-01 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_rename_section1_featuredpost_add_more_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='birthday',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(null=True, verbose_name='date_of_birth'),
        ),
        migrations.AlterField(
            model_name='post',
            name='add_more',
            field=models.CharField(choices=[('Recent', 'Recent'), ('Popular', 'Popular'), ('Trending', 'Trending'), ('Latest Posts', 'Latest Posts')], default='Recent', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='section',
            field=models.CharField(choices=[('Recent', 'Recent'), ('Popular', 'Popular'), ('Trending', 'Trending'), ('Latest Posts', 'Latest Posts')], default='Recent', max_length=200, null=True),
        ),
    ]
