# Generated by Django 3.0.11 on 2024-05-25 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0028_auto_20240525_0402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featuredpost',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.AddField(
            model_name='featuredpost',
            name='first_content',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='featuredpost',
            name='writer',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='first_content',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='writer',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
