# Generated by Django 3.0.11 on 2024-05-25 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0029_auto_20240525_0405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredpost',
            name='first_content',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='first_content',
            field=models.TextField(max_length=300, null=True),
        ),
    ]
