# Generated by Django 3.0.11 on 2024-07-12 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0031_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Message',
        ),
    ]
