# Generated by Django 3.0.11 on 2024-08-10 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0035_auto_20240805_0825'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer', models.CharField(max_length=200, null=True)),
                ('content', models.TextField(max_length=300)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('1', 'Draft'), ('2', 'Publish')], default=1, max_length=100, null=True)),
            ],
        ),
    ]
