# Generated by Django 3.0.11 on 2024-08-10 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0036_dailyreview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyreview',
            old_name='writer',
            new_name='doctor',
        ),
        migrations.RemoveField(
            model_name='dailyreview',
            name='created_on',
        ),
        migrations.AddField(
            model_name='dailyreview',
            name='title',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
