# Generated by Django 3.0.11 on 2024-08-10 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0037_auto_20240810_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreview',
            name='image',
            field=models.ImageField(blank=True, default='blank-profile-picture.png', null=True, upload_to='image/'),
        ),
    ]
